language: node_js

node_js:
    - 14

script:
    - yarn build

deploy:
    provider: npm
    email: apixelvisualsofficial@gmail.com
    api_key:
        secure: EWK3hSlzhaYPcBXAvkfWbRr/yRXbGUBMl7EFBX9Xs2r19wGWwmPM3L/gZu2CUSsdpgEGhn7a+Iu6vrxHvqCxEg1/MqH3/tNsc/bqV+ng3msc/gcmXtrXkq6RalPEmCV5gNilAPN6rSL4PHnFCK++oPO3QCQYoGgCUUmq1ymBWYTqwsZ1y923BpTHuZgZsEcMVm4K8/hv9US8YVXmGV7GiHhS5ZS6zKWqmDcp1ricKMZmnSTGHAa3iiwEI2ejJVZ+yXRAMHomidcRRfLUfuNP31fPrQYJfhmbCri9uyZ+Vk2XOqSXrXjWlfB6HJ4ShCSwSe3aF1xaw8225UUVdNOEZz9iMM1GJmm2aZV+OXcUYimMoz8jEyrTRiWiY2ymOXamfP1R8PtvuWghXNLIxR/ZuSLqYTeecB/v+x45w0idVxMFiB0ifxoHOPJXt+6QYYTaxcE+ohqvJ5i4pKgohef/Urs2Jq2qYS6lErWJO1SfTaCrNKxTFOpcHm5GVH9Det95C/J/X4WgZB7AXJiESES3GpIQWV4q+KWJ99yoiqckZHSe4hp5AMVONmozYMORE/cMCPgyEKDoq9cauc8JVO55kpJbDAS6mobwR+ftfIE+fYdo3aG1h3qPP4PL0cDeMtAwR8AEQbm++DKhbkFE4fBliyHsymX9iI/mm95zgriO1d4=
    on:
        repo: APixelVisuals/typedoc-frontend
        branch: master
        tags: true
    skip_cleanup: true